# thanks https://github.com/ashishb/adb-enhanced/blob/master/.travis.yml
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - Action=lint
  - Action=install

before_script:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - if [ $Action == "lint" ]; then
    ./scripts/lint_check_python3.sh;
    fi

  - if [ $Action == "install" ]; then
    python3 setup.py install;
    fi

matrix:
  include:
    # Source: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
    # Source: https://stackoverflow.com/a/28751112/434196
    - name: Test Python 3 and Android API 16
      language: android
      sudo: true
      jdk: oraclejdk8
      env:
        global:
          - DX_HEAP_SIZE=2048
          # 16 is the fastest as per
          # https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62
          - ANDROID_API_LEVEL=16
          - ANDROID_EMU_API_LEVEL=22
          - ANDROID_ABI=armeabi-v7a
          - QEMU_AUDIO_DRV=none # Remove audio
          - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
      android:
        components:
          - tools
          - platform-tools
          - android-$ANDROID_API_LEVEL
          - android-$ANDROID_EMU_API_LEVEL
          # Specify at least one system image
          - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
      before_script:
        - set -eo pipefail
        # Ensure python3.6 is installed
        - ./scripts/install_python36.sh
        - python --version
        - python -m pip install --user --upgrade pip
        - python -m pip install --user setuptools
        # Android setup
        - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
        # -noaudio is not supported by this version of the emulator
        - emulator -avd test -no-window -no-boot-anim &
      script:
        - python -m pip install --user -r requirements.txt
        - android-wait-for-emulator
        - python -m pytest -v . --durations=0

    # Source: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
    # Source: https://stackoverflow.com/a/28751112/434196
    - name: Test Python 3 and Android API 24
      language: android
      sudo: true
      jdk: oraclejdk8
      # https://docs.travis-ci.com/user/languages/android/#caching
      cache:
        directories:
          # Android SDK
          - $HOME/android-sdk-dl
          - $HOME/android-sdk
          # Android build cache (see http://tools.android.com/tech-docs/build-cache)
          - $HOME/.android/build-cache
      env:
        global:
          - DX_HEAP_SIZE=2048
          # 16 is the fastest as per
          # https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62
          - ANDROID_API_LEVEL=24
          - ANDROID_EMU_API_LEVEL=24
          - ANDROID_ABI=armeabi-v7a
          - QEMU_AUDIO_DRV=none # Remove audio
          - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
          - ANDROID_HOME=$HOME/android-sdk
          # "emulator" commands needs this
          - ANDROID_SDK_ROOT=$HOME/android-sdk

      install:
        - set -e
        - touch $HOME/.android/repositories.cfg
        # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
        # Latest version available here: https://developer.android.com/studio/#command-tools
        - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
        - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

        # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-$ANDROID_API_LEVEL" > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager "system-images;android-$ANDROID_API_LEVEL;default;$ANDROID_ABI" > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager "system-images;android-$ANDROID_EMU_API_LEVEL;default;$ANDROID_ABI" > /dev/null

      before_script:
        - set -eo pipefail
        # Ensure python3.6 is installed
        - ./scripts/install_python36.sh
        - python --version
        - python -m pip install --user --upgrade pip
        - python -m pip install --user setuptools
        # Android setup
        - echo no | $HOME/android-sdk/tools/bin/avdmanager create avd --force -n test --tag default --abi $ANDROID_ABI --package "system-images;android-$ANDROID_API_LEVEL;default;$ANDROID_ABI"
        - ls -al $HOME
        # Directly calling emulator command fails, taking fix from here.
        # https://www.bram.us/2017/05/12/launching-the-android-emulator-from-the-command-line/
        - alias emulator=$HOME/android-sdk/tools/emulator
        # -noaudio is not supported by this version of the emulator
        - emulator -avd test -no-window -no-boot-anim &
      script:
        - python -m pip install --user -r requirements.txt
        - android-wait-for-emulator
        - python -m pytest -v . --durations=0
        # We can even run only these two tests which are not triggered below API 23
        # - python -m pytest -v tests/adbe_tests.py  --durations=0 -k test_permissions_grant_revoke
        # - python -m pytest -v tests/adbe_tests.py  --durations=0 -k test_doze
# Good .travis.yml files to learn from
# https://github.com/ruboto/ruboto/blob/master/.travis.yml
# https://raw.githubusercontent.com/BanzaiMan/travis_production_test/bc25099f9bd413c43cee9e7118e8eee4b1448fd6/.travis.yml
# Android build caching https://medium.com/@bod/cache-your-android-sdk-with-travis-c816b9264708
