language: android
sudo: required
jdk: oraclejdk8

env:
  - PYVER=3.6.0
  # - PYVER=3.7.2


android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    # - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17

install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install android-tools-adb
  - sudo python3.6 -m pip install androidtool
  # - cd $TRAVIS_BUILD_DIR
  - sudo python3.6 -m pip install -r requirements.txt

before_script:
# Emulator Management: Create, Start and Wait
  - python3.6 --version
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  # - adb shell input keyevent 82 &

  # - cd $TRAVIS_BUILD_DIR/$TRAVIS_REPO_SLUG
  # /home/travis/build/lite3/adbtool/lite3/adbtool
  - cd $TRAVIS_BUILD_DIR
  - chmod +x -R .
  - export PYTHONPATH="$(pwd)"
script:
  - ls -lha /usr/local/android-sdk/platform-tools
  - python3.6 -m pytest
  # - python -m adbtool.adbtool
  # - python -m adbtool.adbtool device -l
  # - python -m adbtool.adbtool device -h
  # - python -m adbtool.adbtool device -d 1 2
  # - python -m adbtool.adbtool device -d em
  # - python -m adbtool.adbtool push -h
  # - python -m adbtool.adbtool install -h
  # - python -m adbtool.adbtool install test/adbtooltest.apk
